### ISSUE TITLE
glue_privesc scenario terraform error issue

### ISSUE THREAD

**Issue by jinsu9758** [BoB12-C-G-V/cloudgoat#6]
Error: Duplicate resource "aws_security_group_rule" configuration
│ 
│   on sg.tf line 15:
│   15: resource "aws_security_group_rule" "attache_source_group" {
│ 
│ A aws_security_group_rule resource named "attache_source_group" was already declared at
│ rds.tf:67,1-58. Resource names must be unique per type in each module.
╵

╷
│ Error: Duplicate resource "aws_security_group_rule" configuration
│ 
│   on sg.tf line 15:
│   15: resource "aws_security_group_rule" "attache_source_group" {
│ 
│ A aws_security_group_rule resource named "attache_source_group" was already declared at
│ rds.tf:67,1-58. Resource names must be unique per type in each module.
╵

[cloudgoat] Error while running `terraform init`.
    exit code: 1
    stdout: None
    stderr: None

**Comment by Hosim33** [comment]
다른 Repo에서 작업 중이라 예전 코드여서 발생한 오류
