### ISSUE TITLE
glue_privesc scenario create terraform issue

### ISSUE THREAD

**Issue by jinsu9758** [BoB12-C-G-V/cloudgoat#7]
Error: creating EC2 Instance: InvalidParameter: Security group sg-000d0f7eb0e93817a and subnet subnet-0d77b0ea70f0dd160 belong to different networks.
│ 	status code: 400, request id: b0530485-b2e5-47c8-ab78-2d9afa3eccc6
│ 
│   with aws_instance.cg-ubuntu-ec2,
│   on ec2.tf line 14, in resource "aws_instance" "cg-ubuntu-ec2":
│   14: resource "aws_instance" "cg-ubuntu-ec2" {
│ 
╵
╷
│ Error: attaching policy arn:aws:iam::aws:policy/AWSLambdaBasicExecutionRole to IAM Role s3_to_gluecatalog_lambda_role: NoSuchEntity: Policy arn:aws:iam::aws:policy/AWSLambdaBasicExecutionRole does not exist or is not attachable.
│ 	status code: 404, request id: 7f68dcae-aa9a-45b8-9d28-53edff0031e3
│ 
│   with aws_iam_role_policy_attachment.s3_to_gluecatalog_lambda_role_policies["arn:aws:iam::aws:policy/AWSLambdaBasicExecutionRole"],
│   on iam.tf line 171, in resource "aws_iam_role_policy_attachment" "s3_to_gluecatalog_lambda_role_policies":
│  171: resource "aws_iam_role_policy_attachment" "s3_to_gluecatalog_lambda_role_policies" {
│ 
╵
╷
│ Error: creating Lambda Function (s3_to_gluecatalog): operation error Lambda: CreateFunction, https response error StatusCode: 400, RequestID: 69adfff5-26d2-4d04-b591-3873efea9e85, InvalidParameterValueException: Could not unzip uploaded file. Please check your file, then try to upload again.
│ 
│   with aws_lambda_function.s3_to_gluecatalog,
│   on lambda.tf line 1, in resource "aws_lambda_function" "s3_to_gluecatalog":
│    1: resource "aws_lambda_function" "s3_to_gluecatalog" {
│ 
╵
╷
│ Error: creating RDS DB Instance (terraform-20231110142425143800000008): InvalidParameterValue: DBName must begin with a letter and contain only alphanumeric characters.
│ 	status code: 400, request id: 0a489347-53be-4d8b-949c-62225a67d25a
│ 
│   with aws_db_instance.cg-rds,
│   on rds.tf line 1, in resource "aws_db_instance" "cg-rds":
│    1: resource "aws_db_instance" "cg-rds" {
│ 
╵
╷
│ Error: Conflicting configuration arguments
│ 
│   with aws_security_group_rule.attache_source_group-in,
│   on rds.tf line 124, in resource "aws_security_group_rule" "attache_source_group-in":
│  124:   cidr_blocks = ["0.0.0.0/0"]
│ 
│ "cidr_blocks": conflicts with source_security_group_id
╵
╷
│ Error: Conflicting configuration arguments
│ 
│   with aws_security_group_rule.attache_source_group-in,
│   on rds.tf line 127, in resource "aws_security_group_rule" "attache_source_group-in":
│  127:   source_security_group_id = aws_security_group.cg-ec2-rds-security-group.id
│ 
│ "source_security_group_id": conflicts with cidr_blocks
╵
╷
│ Error: Conflicting configuration arguments
│ 
│   with aws_security_group_rule.attache_source_group-out,
│   on rds.tf line 150, in resource "aws_security_group_rule" "attache_source_group-out":
│  150:   cidr_blocks = ["0.0.0.0/0"]
│ 
│ "cidr_blocks": conflicts with source_security_group_id
╵
╷
│ Error: Conflicting configuration arguments
│ 
│   with aws_security_group_rule.attache_source_group-out,
│   on rds.tf line 153, in resource "aws_security_group_rule" "attache_source_group-out":
│  153:   source_security_group_id = aws_security_group.cg-rds-ec2-security-group.id
│ 
│ "source_security_group_id": conflicts with cidr_blocks
╵
╷
│ Error: creating S3 Bucket (cg-data-s3-bucket-glue-privesc-cgidv3zfvds9c0) ACL: operation error S3: PutBucketAcl, https response error StatusCode: 400, RequestID: GVJD0XES632E2RC3, HostID: DuwSeK1XwvBOXiAeqt9zHbfv9crpZaG+78HIRu75+X4Y1VyMI5jVb43SduGVHrcHc/hRc0EcEEE=, api error AccessControlListNotSupported: The bucket does not allow ACLs
│ 
│   with aws_s3_bucket_acl.cg-data-s3-bucket-acl,
│   on s3.tf line 20, in resource "aws_s3_bucket_acl" "cg-data-s3-bucket-acl":
│   20: resource "aws_s3_bucket_acl" "cg-data-s3-bucket-acl" {
│ 
╵
╷
│ Error: putting S3 Bucket (cg-data-from-web-glue-privesc-cgidv3zfvds9c0) Policy: operation error S3: PutBucketPolicy, https response error StatusCode: 403, RequestID: GVJAZ6G0H4QS0X37, HostID: fhkgglfFURTMlkH4q9Y4ys9AtXf/2XC4XfX8h0MswYBeb2AEAt/D6bCwBBzO2+6GrSOW2ovFgcwI211+wcX3Jw==, api error AccessDenied: Access Denied
│ 
│   with aws_s3_bucket_policy.putobject,
│   on s3.tf line 62, in resource "aws_s3_bucket_policy" "putobject":
│   62: resource "aws_s3_bucket_policy" "putobject" {
│ 
╵
╷
│ Error: creating EC2 VPC Endpoint (com.amazonaws.us-east-1.glue): InvalidParameter: Route table IDs are only supported for Gateway type VPC Endpoint.
│ 	status code: 400, request id: fdaace36-6f79-4944-90ce-5247430f3932
│ 
│   with aws_vpc_endpoint.glue,
│   on vpc.tf line 8, in resource "aws_vpc_endpoint" "glue":
│    8: resource "aws_vpc_endpoint" "glue" {
│ 
╵

[cloudgoat] Error while running `terraform apply`.
    exit code: 1
    stdout: None
    stderr: None

**Comment by Hosim33** [comment]
해결 완료
