### ISSUE TITLE
glue_privesc scenario create issue

### ISSUE THREAD

**Issue by jinsu9758** [BoB12-C-G-V/cloudgoat#8]
Error: file provisioner error
│ 
│   with aws_instance.cg-ubuntu-ec2,
│   on ec2.tf line 27, in resource "aws_instance" "cg-ubuntu-ec2":
│   27:   provisioner "file" {
│ 
│ timeout - last error: SSH authentication failed (ec2-user@3.84.180.238:22): ssh: handshake
│ failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods
│ remain
╵
╷
│ Error: attaching policy arn:aws:iam::aws:policy/AWSLambdaBasicExecutionRole to IAM Role s3_to_gluecatalog_lambda_role: NoSuchEntity: Policy arn:aws:iam::aws:policy/AWSLambdaBasicExecutionRole does not exist or is not attachable.
│ 	status code: 404, request id: 116b0d87-2243-4b75-8528-3f59513168d1
│ 
│   with aws_iam_role_policy_attachment.Lambda_Basic_Execution,
│   on iam.tf line 170, in resource "aws_iam_role_policy_attachment" "Lambda_Basic_Execution":
│  170: resource "aws_iam_role_policy_attachment" "Lambda_Basic_Execution" {
│ 
╵
╷
│ Error: creating Lambda Function (s3_to_gluecatalog): operation error Lambda: CreateFunction, https response error StatusCode: 400, RequestID: d71de359-5a1a-42f2-85c2-dce81943d23d, InvalidParameterValueException: Could not unzip uploaded file. Please check your file, then try to upload again.
│ 
│   with aws_lambda_function.s3_to_gluecatalog,
│   on lambda.tf line 1, in resource "aws_lambda_function" "s3_to_gluecatalog":
│    1: resource "aws_lambda_function" "s3_to_gluecatalog" {
│ 
╵
╷
│ Error: creating RDS DB Instance (terraform-2023111111492864260000000b): InvalidSubnet: No default subnet detected in VPC. Please contact AWS Support to recreate default Subnets.
│ 	status code: 400, request id: 9042dd26-793d-40ed-b0a4-472c95a23fc3
│ 
│   with aws_db_instance.cg-rds,
│   on rds.tf line 1, in resource "aws_db_instance" "cg-rds":
│    1: resource "aws_db_instance" "cg-rds" {
│ 
╵
╷
│ Error: putting S3 Bucket (cg-data-from-web-glue-privesc-cgiduh6mwmb1r9) Policy: operation error S3: PutBucketPolicy, https response error StatusCode: 403, RequestID: AERM47P6H1MJ6FRD, HostID: /qrlbAM6uJOW55VhLLauZJEKHUrSDgfe85r8Vjv+YlBbjBWe7rvHr095qhMM/LHcDtIIPoRg5DIdbK0L+4QaKePnO5pBHM6552PhXkz1VA4=, api error AccessDenied: Access Denied
│ 
│   with aws_s3_bucket_policy.putobject,
│   on s3.tf line 70, in resource "aws_s3_bucket_policy" "putobject":
│   70: resource "aws_s3_bucket_policy" "putobject" {
│ 
╵

[cloudgoat] Error while running `terraform apply`.
    exit code: 1
    stdout: None
    stderr: None

**Comment by Hosim33** [comment]
AWSLambdaBasicExecutionRole error 해결 완료
